# Default values for hlf-kube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

retryCount: 4

hyperledgerVersion: 1.4.3

# see the Raft sample in the README for how to enable TLS
tlsEnabled: false

# use actual domain names like peer0.atlantis.com instead of internal service names
# this should be set to true for TLS
useActualDomains: false

# adds additional DNS entries to /etc/hosts files
# see https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/#adding-additional-entries-with-hostaliases
# this value should be provided if either tlsEnabled or useActualDomains is set to true
# see the Raft sample in the README for how to use this
hostAliases: []

logLevel: info

# not sure if it's possible to change this, but better define here
ordererSystemChannel: aretechainid

flow:
  consortium:
    # should we add new org(s) to existing consortiums?
    enabled: true
    # fill in this array with consortium names to limit adding new org only to these ones
    include: []
  channel:
    # should we add new org(s) to existing channels?
    enabled: true
    # should we add new org(s) to multiple channels in parallel? 
    parallel: true
    # fill in this array with channel names to limit adding new org(s) only to these ones
    include: []
    